name: BacktrackKit
version: 0.3.1
date: 2019-11-07
description: |
    An Extensible, easy to understand backtracking framework

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf Wilson
      url: http://wilf.me

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf Wilson
      url: http://wilf.me

contributors:
    - name: Markus Pfeiffer
      url: https://www.morphism.de/~markusp

GAP: ">= 4.9"

needed-pkgs:
    - name: "datastructures"
      version: ">= 0.2.2"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">= 1.0.0"
      url: "https://gap-packages.github.io/Digraphs"

www: https://peal.github.io/BacktrackKit/
readme: README.md
packageinfo: https://peal.github.io/BacktrackKit/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/peal/BacktrackKit/releases/download/v0.3.1/BacktrackKit-0.3.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>JW19</span>]   <b class='BibAuthor'>Jefferson, C. and Wilson, W.</b>,
     <i class='BibTitle'>BacktrackKit, An Extensible, easy to understand backtracking framework,
             Version 0.3.1</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://peal.github.io/BacktrackKit/">https://peal.github.io/BacktrackKit/</a></span>.
    </p>
    

bibtex: |
    @misc{ BacktrackKit0.3.1,
      author =           {Jefferson, C. and Wilson, W.},
      title =            {{BacktrackKit},  An  Extensible,  easy  to  understand
                          backtracking framework, {V}ersion 0.3.1},
      month =            {Nov},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href           {https://peal.github.io/BacktrackKit/}
                          {\texttt{https://peal.github.io/}\discretionary
                          {}{}{}\texttt{BacktrackKit/}}},
      printedkey =       {JW19}
    }

