name: BacktrackKit
version: 0.1
date: 2018-11-13
description: |
    An Extensible, easy to understand backtracking framework

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.9"

www: https://ChrisJefferson.github.io/BacktrackKit/
readme: README.md
packageinfo: https://ChrisJefferson.github.io/BacktrackKit/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/ChrisJefferson/BacktrackKit/releases/download/v0.1/BacktrackKit-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Jef18</span>]   <b class='BibAuthor'>Jefferson, C.</b>,
     <i class='BibTitle'>BacktrackKit, An Extensible, easy to understand backtracking framework,
             Version 0.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://ChrisJefferson.github.io/BacktrackKit/">https://ChrisJefferson.github.io/BacktrackKit/</a></span>.
    </p>
    

bibtex: |
    @misc{ BacktrackKit0.1,
      author =           {Jefferson, C.},
      title =            {{BacktrackKit}, An Extensible, easy to understand backtracking framework, {V}ersion 0.1},
      month =            {Nov},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href                                                          {https://ChrisJefferson.github.io/BacktrackKit/}
                          {\texttt{https://ChrisJefferson.github.io/}\discretionary {}{}{}\texttt{BacktrackKit/}}},
      printedkey =       {Jef18}
    }

